### ISSUE TITLE
スペース2つでネストされない

### ISSUE THREAD

**Issue by ngwork0301** [ngwork0301/mkdocs-blog#22]
現象
-----
スペース２つでリストがネストされない。４つ必要。
```
* ネスト１
  * ネスト２
```
こう書いても、以下になる
↓
* ネスト１
 * ネスト２ 

本来の動作
-----
GithubのMarkdownのようにスペース２つでリストがネストされるようにする。
* ネスト１
  * ネスト２ 

対処
-----
* mdx_truly_sane_listsをインストール
``` bash
$ pip install mdx_truly_sane_lists
```

* mkdocs.ymlに以下を追記
``` yaml
markdown_extensions:
    - mdx_truly_sane_lists:
        nested_indent: 2
```
* ※[stakiranさんのブログ](https://stakiran.hatenablog.com/entry/2018/08/02/202816) を参考にさせていただきました（感謝！）

備考
-----
* Python-markdownはスペース４つが正義らしい。
* そのポリシーに乗っ取るなら直さないのが正しい。（2つで済むならそっちほうが楽なので、仕様のほうを直すべきではと私は考えたため、直すことにした）
