### ISSUE TITLE
検索ができない

### ISSUE THREAD

**Issue by ngwork0301** [ngwork0301/mkdocs-blog#26]
## 現象
* 検索formにいれても検索が動作しない。
* 日本語検索ができない

## 対処
* 以下を参照に、mkdocs.ymlを更新
[Setting up site search - Material for MkDocs](https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/)
* 日本語検索は、plugins/searchにenとjaを入れておいたが、jaのみにしないとダメだった
``` yaml
plugins:
    - search:
        lang:
          - en       # ← enは消す
          - ja
```

## 関連issue
#27
