### ISSUE TITLE
更新日付がISO形式にならない

### ISSUE THREAD

**Issue by ngwork0301** [ngwork0301/mkdocs-blog#59]
## 現象
以下のように `YYYY年MM月DD日` 形式になるべきものがそうなっていない  
![スクリーンショット 2021-11-04 6 32 49](https://user-images.githubusercontent.com/36479812/140196067-e2eb38c0-142a-41a8-9b34-030ac41bebf0.png)

## 原因
2803d51bb13347c86cec440477cff9caf9338696 での更新により、mkdocsのベースバージョンとプラグインのバージョンアップによる影響。  
形式設定は、以下で指定している
``` yml : mkdocs.yml
plugins:
    - git-revision-date-localized:
        type: 
          iso_datetime
```
